name: CheckGeolocationsDuplications
on: pull_request

permissions:
  contents: read

jobs:
  GeolocationsDuplicationsValidator:
    name: GeolocationsDuplicationsValidator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - working-directory: page
        run: npm ci
      - name: Validate Geolocations duplication
        working-directory: tools
        run: |
          npm ci
          node mdValidator.js
          node mdParser.js
          node geoCodes.js
          node validateGeolocations.js
      - name: Run Tests
        working-directory: page
        run: npm test -- --run
