name: CheckGeoCodes
on: pull_request

permissions:
  contents: read

jobs:
  MdValidator:
    name: GeoCodesValidator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - working-directory: page
        run: npm install -D
      - name: Validate GeoCodes
        working-directory: tools
        run: |
          npm install -D
          node mdValidator.js
          node mdParser.js
          node geoCodes.js
      - name: Run Tests
        working-directory: page
        run: npm test -- --run
