name: Generate Tags

on:
  schedule:
    # Runs every day
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    if: github.repository == 'scraly/developers-conferences-agenda'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - working-directory: page
        run: npm install -D
      - name: Generate Tags
        working-directory: tools
        env:
          OVH_AI_ENDPOINTS_ACCESS_TOKEN: ${{ secrets.OVH_AI_ENDPOINTS_ACCESS_TOKEN }}
          OVH_AI_ENDPOINTS_MODEL_URL: ${{ vars.OVH_AI_ENDPOINTS_MODEL_URL }}
          OVH_AI_ENDPOINTS_MODEL_NAME: ${{ vars.OVH_AI_ENDPOINTS_MODEL_NAME }}
        run: |
          npm install -D
          node mdValidator.js
          node mdParser.js
          node generateAITagsv2.js
      - name: Run Tests
        working-directory: page
        run: npm test -- --run
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          token: ${{ secrets.PAT }}
          commit-message: generate new tags
          title: Generate Tags
          base: main
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: generate-tags
          delete-branch: true
          body: |
            This PR was generated via GH action
            - Generates tags
          draft: false
