name: Deploy GitHub Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - working-directory: page
        run: npm install -D
      - name: Parse Markdowns
        working-directory: tools
        run: |
          npm install -D
          node mdValidator.js
          node mdParser.js
          node generateIcs.js
          node generateIcs4OpenedCfps.js
          node generateRSS.js
          node geoCodes.js
      - name: Run Tests
        working-directory: page
        run: npm test -- --run
      - working-directory: page
        run: npm run build
      - name: Make all-*.json files available at the site root
        working-directory: tools
        run: |
          mv ../page/src/misc/all-events.json ../page/build/all-events.json
          mv ../page/src/misc/all-cfps.json ../page/build/all-cfps.json
          mv ../page/src/misc/*.ics ../page/build/
          mv ../page/src/misc/feed-events.* ../page/build/
          mv ../page/src/misc/og-preview.png ../page/build/
      - name: Deploy to GitHub Pages
        if: github.ref_name == 'main'
        uses: crazy-max/ghaction-github-pages@59173cb633d9a3514f5f4552a6a3e62c6710355c # v2.7.0
        with:
          target_branch: gh-pages
          build_dir: page/build/
          keep_history: true
          fqdn: developers.events # CNAME
          jekyll: false # Solve website 404
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
