name: Update CFP Status

on:
  schedule:
    # Runs every day
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    if: github.repository == 'scraly/developers-conferences-agenda'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - working-directory: page
        run: npm ci
      - name: Fix CFP color
        working-directory: tools
        run: |
          npm ci
          node mdValidator.js
          node mdParser.js
          node fixCFPColor.js
          node geoCodes.js
      - name: Run Tests
        working-directory: page
        run: npm test -- --run
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          token: ${{ secrets.PAT }}
          commit-message: update cfp status color
          title: Update CFP status color
          base: main
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-cfp-color
          delete-branch: true
          body: |
            This PR was generated via GH action
            - Updates CFP status color green to red
            - Generates geo locations
          draft: false
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3.0.0
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
